### ISSUE TITLE
In Next.js 14.2.0 dev mode, initialState gets called with an instance that does not call `registerUpdateListener` callbacks

### ISSUE THREAD

**Issue by petyosi** [mdx-editor/lexical-issue#1]
@etrepum tagging you here, I can promote that into the Lexical repo as well. 

Please check [the readme](https://github.com/mdx-editor/lexical-issue) for repro steps. This is a weird problem - I am not sure if it's Lexical or Next.js, or maybe something they picked from a recent React version.

**Comment by etrepum** [comment]
Is it really a problem? The only way I can see this order mattering is if the code is doing something that violates the rules of react that strict mode is trying to help you discover

**Comment by petyosi** [comment]
Fixed in https://github.com/mdx-editor/editor/commit/c533de7f0383ebc8f71f0c79a505467bcef8ab99
